### ISSUE TITLE
[Theme Request] Default OneDark Pro

### ISSUE THREAD

**Issue by ArKeid0s** [doki-theme/doki-master-theme#119]
## Who/What do you want to be featured?
Just the color theme of OneDark Pro I am using your theme for the sticker and background features but I like classic syntax colors like default Visual Studio color theme and OneDark Pro

### What do they look like?
[image](https://user-images.githubusercontent.com/46865726/133135122-53ca1ec5-76b5-4c08-bd8c-3ba6c33f5b05.png)

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
Thank you for this theme

**Comment by Unthrottled** [comment]
Hey!

So I am assuming you are talking about using Visual Studio.

Good News is you don't need my plugin, you can use your existing One Dark Theme and just use [Claudia IDE](https://github.com/buchizo/ClaudiaIDE). 

I'm going to close this issue because I am not supporting any different syntax coloration schemes that differ from mine _and_ are not based on a character. 

Let me know if I am missing something, and I'll try to point you in the right direction.
