### ISSUE TITLE
[Theme Request] Kagamihara Nadeshiko

### ISSUE THREAD

**Issue by LiuTianXiangP** [doki-theme/doki-master-theme#135]
### What do they look like?

![image](https://user-images.githubusercontent.com/69110887/144778377-d36f3e2c-b75e-42db-8255-e8840614bab6.png)
![image](https://user-images.githubusercontent.com/69110887/144778566-c86c0d13-ba9b-4c02-bec1-ad85534e4270.png)

## What type of theme?
- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
  If we had Shima Rin, then Nadeshiko is a must!
  
Color pallete should be something comfy, not high-contrast.

Note: yes, I do simp for her. And I'm proud of it.

**Comment by Unthrottled** [comment]
> ![Cinnamon Bun](https://user-images.githubusercontent.com/69110887/144778566-c86c0d13-ba9b-4c02-bec1-ad85534e4270.png)

:point_up: This is one of my Apple Watch faces.

Even though Nadeshiko is best girl, I already have a bunch of themes based on girls with pink hair. I guess I might have to try harder to find an outfit that might make a good & unique color palette.

Though I suppose I could make one up, like I did with Rin's backround, which isn't anything like the one in the anime. 

![1flrfli3btg01](https://user-images.githubusercontent.com/15972415/144864633-c3fa8723-a1eb-4835-9301-d8343e79d304.jpg)

I dunno, stay tuned!

**Comment by Unthrottled** [comment]
Thanks for the suggestion! 

That looks a lot like Ram from Re:Zero though

![Ram](https://raw.githubusercontent.com/doki-theme/doki-theme-visualstudio/main/readmeAssets/screens/themes/ram_dark_code.png)

Which is convenient, because you could just change out Ram's assets for Nadeshiko.

If Nadeshiko is getting her own theme, I want it to be unique and special. I'll probably come up with something.

**Comment by Unthrottled** [comment]
> Do I have enough dark pink themes? 

 Yes.

> Does Nadeshiko's theme look similar to others? 

Yes.

> Do I care? 

**No.**

![image](https://user-images.githubusercontent.com/15972415/149677801-1945deca-4be9-4821-bc26-669079f0d5dc.png)

I think it turned out well. Anyways, I figured I would share what the new theme will look like. It will probably take me about a month to finish the other themes, before I release Nadeshiko. Making the background art takes forever.
