### ISSUE TITLE
[Question] When will be added a new theme? 

### ISSUE THREAD

**Issue by Dragon-0609** [doki-theme/doki-master-theme#272]
## Additional Information (Optional)
I looked to last theme addition date and saw that it was in August 2022. I'm interested in when a new theme will be added

**Comment by Unthrottled** [comment]
Hey! Thanks for the question!

It seems like just yesterday since released it. 

I am super happy with https://github.com/doki-theme/doki-master-theme/releases/tag/v88.0

Right now, I am taking care of my family and my newborn baby. I don't see myself adding a new theme anytime soon. 

I might consider it in the future, but right now I've got what I want :)

**Comment by Dragon-0609** [comment]
That’s wonderful news! Wishing you and your family all the happiness.
