### ISSUE TITLE
[Theme Request] Gray - From: Lord El-Melloi II Case Files

### ISSUE THREAD

**Issue by ProxyNeko** [doki-theme/doki-master-theme#49]
## Who/What do you want to be featured?
Gray from [Lord El-Melloi II Case Files](https://www.crunchyroll.com/en-gb/lord-el-melloi-iis-case-files-rail-zeppelin-grace-note)

### What do they look like?
Her normal form:
![image](https://user-images.githubusercontent.com/19393068/109704024-0ab2e200-7b8e-11eb-8f95-374517b8472e.png)
![image](https://user-images.githubusercontent.com/19393068/109701088-890d8500-7b8a-11eb-936e-0d405be43821.png)

Her hood up, power unlocked form:
![image](https://user-images.githubusercontent.com/19393068/109701378-d7228880-7b8a-11eb-973c-8ecc09192e02.png)

A figure since I couldn't find her hood down powered up form:
![image](https://user-images.githubusercontent.com/19393068/109702783-99befa80-7b8c-11eb-9f10-ddc291eebe0a.png)

Best chibi forms of her I could find:
![image](https://user-images.githubusercontent.com/19393068/109703311-397c8880-7b8d-11eb-8e41-c38df65e47f6.png)
![image](https://user-images.githubusercontent.com/19393068/109703377-4dc08580-7b8d-11eb-9d2f-cb7dc172a8fa.png)

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information
I'm looking for a dark-ish grey look and feel with plenty of hints of the emerald glow of her eyes, then the gold, pink and blue that follows her in the show for the rest of the sort of accent I think.
It's a really great show but a shame it's only a side story to the main Fate series so I recommend you give it a watch some time :D

**Comment by Unthrottled** [comment]
Very Nice!

I just started my adventure in the Fate anime series. Seeing stuff this makes me realize, I'm probably going to be watching Fate for a while :sweat_smile: 

I'll agree that she does have a nice color palette (plus she is cute too). I'll be keeping her in mind, thanks!

**Comment by ProxyNeko** [comment]
That's great to hear, I've been using Rin as my theme for ages thought it would be a nice change of colour xD Keep an eye out for Saber the King of Knights when you come across her, there is a bit of backstory/lore between her and Gray should you have time to check out the wikis/story :D

**Comment by Unthrottled** [comment]
I'm currently work for neat background art. 

I found this. Was planning on using this. I'll probably omit the scythe  so that Gray is the primary focus of the background art. I'll probably keep the dope blue wisp stuff.

![a6d5d3b983ca7711aa4b87f5488ac4e9](https://user-images.githubusercontent.com/15972415/115115489-506b1480-9f5a-11eb-8519-99b7cf7089fd.jpg)

Was wondering if you new of a better piece of art (I didn't look very hard :sweat_smile: )

**Comment by ProxyNeko** [comment]
Honestly I think that's one of the better poses out there, even though there is lots of art of her and images the good ones are really hard to find or not quite good enough (The show doesn't seem to have the praise that it deserves like say Rin Tohsaka for example making it harder to find good images)

However I like your idea of removing the scythe to make her the main focus, the third image from the top that I posted was the only decent one I could find from the show itself with wisps around her so you've one upped me there xD

I know her arm is under her cloak but I still feel like I need to ask where it is lol also my apologies for the late reply, been a busy few days of chaos :s

**Comment by Unthrottled** [comment]
Cool, no worries, I figured I'd ask and see (you never know unless you ask). At the rate that I am going, I'll probably be done within the next couple of weeks. Creating the backgrounds takes the longest (but I am getting faster!). I can hook you up with an early access version of the Intellij plugin, if that is what you are using and want to test out.

**Comment by ProxyNeko** [comment]
Never hurts to try :) It's always nice to see self improvement in speed and skill :D just don't do what I did and burn yourself out in the process xD but yeah sure thing I'll be a guinea pig, never mind helping out when I'm using the tools anyway :) just give me a prod when you feel ready!

**Comment by Unthrottled** [comment]
Aight. I'll post a beta when I am ready. All of the color-schemes are done, they are just using clear assets. When I publish the assets, the plugin will eventually pick up the changes. 

You'll be able to use the beta after manually installing. When I publish the final product, your IDE will prompt for an automatic update.

> just don't do what I did and burn yourself out in the process

Noted! I've got a process that prevents me from overworking myself, I appreciate the heads up though! (I've also considered I might be fundamentally broken too).

**Comment by Unthrottled** [comment]
![Screenshot from 2021-04-25 10-30-00](https://user-images.githubusercontent.com/15972415/116002296-bab93000-a5be-11eb-9755-bb378e762bde.png)

@ProxyNeko This is what I've got :point_up: 

I think her theme turned out well, and I look forward to coding with her. That being said, I haven't spent a day or two using the theme, so I haven't caught all the small issues yet.

[doki-theme-jetbrains-14.3.1.zip](https://github.com/doki-theme/doki-master-theme/files/6372511/doki-theme-jetbrains-14.3.1.zip)

:point_up: This is the version of the plugin that has her theme (she's at the bottom because `Lord El-Melloi II Case Files` is more work to type than `TypeMoon`, I am also debating on putting the rest of the Fate Characters in this group too.) BTW, I've finished Tohru & Miia so their themes are good. I gotta work on Miku, Nino, and Hatsune Miku's assets, so that's whats up.

[Link on how to install](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk)

PS: I tried out the blue wisp stuff, but it didn't really add anything extra IMO. I liked the idea, but it doesn't really vibe well in implementation.

**Comment by ProxyNeko** [comment]
That. Looks. BEAUTIFUL! 
You've been able to do exactly what I was after and with an amazing chibi compared to the ones I found :D 
The colours you've chosen complement it all so nicely I really have to thank you and applaud your hard work once again! 

> ☝️ This is the version of the plugin that has her theme (she's at the bottom because Lord El-Melloi II Case Files is more work to type than TypeMoon, I am also debating on putting the rest of the Fate Characters in this group too.) BTW, I've finished Tohru & Miia so their themes are good. I gotta work on Miku, Nino, and Hatsune Miku's assets, so that's whats up.  

A TypeMoon section would probably be a good idea given how many of them there could be xD it might also be worth extending the size of the dropdown menu in the settings section for the themes also because I find myself scrolling past the ones I'm looking for so often because there are so many now. I'll be sure to give the others a good try out too, thank you for the hard work :3 

If I spot any issues I'll bring them back to this issue to keep them in one place but it looks great in action so far!

**Comment by Unthrottled** [comment]
@ProxyNeko I've got the polished version [posted to GitHub](https://github.com/doki-theme/doki-theme-jetbrains/releases/tag/v15.0.0) if you wanted to update. Otherwise, I'll probably send it to the plugin marketplace later this week.

**Comment by ProxyNeko** [comment]
Sorry for the late reply it's been running smooth as butter so I can wait if needed, been asleep a lot this week trying to fix my sleep schedule xD
Thanks for the update though and keep up the amazing work! :D
