### ISSUE TITLE
Dark Asuna, ZeroTwo, and Mai Sakurajima Combined Theme

### ISSUE THREAD

**Issue by ehAsuna** [doki-theme/doki-master-theme#82]
## Who/What do you want to be featured?
Mai Sakurajima, Asuna, and Zerotwo

### What do they look like?
There are already images for all of them xD. Just want a combined version :p

## What type of theme?
- [ ] Dark Theme

## Additional Information (Optional)
This deserves to be included simply because these are the top 3 waifus and when you combine all three of them you become the ultimate otaku programmer in which you can code anything in as little or long of time you want becasue you have WAIFU POWER!!!!!

**Comment by Unthrottled** [comment]
:thinking: It never occurred to me to ever combine Waifu for a collab theme. It's an interesting idea, but there are a ton of combinations! I don't even know that the look and feel/syntax coloring would look like at the moment.

> these are the top 3 waifus 

I see you fam, and that's just like your opinion. You _did_ included ZeroTwo, so it's a good opinion might I add.

What plugin do you use, VS Code (I think you where the one who suggested dark asuna, right? Think you had the Mai handgun edit profile pic) If that's the case, I think after I get done working on [v11](https://github.com/doki-theme/doki-master-theme/milestone/5), I can add something to VSCode plugin that allows you to set your own custom background/sticker. That way you can create your own image with your waifu ordered how you please. I can also provide the clean assets of your waifu (no outlines/background color) if wanted. 

This way you can level up your weeb game sooner than later. Because I don't think I'll have on official collab theme, but I'll think about it.

**Comment by ehAsuna** [comment]
Yes, I was the one that had suggested Asuna Dark! Also, I love your chrome, github, vscode, and hyper themes! I would like to recommend a repl.it doki theme (if you have time) as well!

So, if you were to add a custom background (and maybe sticker) plugin along with the background assets you use I would be delighted and I'm sure everyone else would too. 

While I'm here I'd like to ask for your help with modifying the style and getting a bit doki on an online wrapper (code.org) which I use a lot. If there's anyway I can message you and ask for your help (discord?) without taking up any of your personal time I'd be delighted to have such to help with issues and such that I face.

**Comment by Unthrottled** [comment]
> I would like to recommend a repl.it doki theme

Noted. However, I think I'll be working on [Visual Studio](https://github.com/doki-theme/doki-theme-vscode/issues/43) after I am done with adding this round of Waifu at the moment.

> While I'm here I'd like to ask for your help with modifying the style and getting a bit doki on an online wrapper (code.org) which I use a lot.

I'm assuming your just wanting to use [Stylus & usercss](https://github.com/openstyles/stylus) to customize the look an feel right? If so are you trying to use the colors provided by this repo? (if so I can show you my build tools n stuff if that's the case). I'd be happy to help.  However, I'd like to get done with this round of themes, but you can shoot me a discord message (unthrottled#0197) and I'll check discord every now and then.

**Comment by ehAsuna** [comment]
I will message you on discord with more info! Thank you so much I really appreciate the help and theme! Much love <3
